import 'package:kiwi_app/Modules/Event.dart';
import 'package:flutter/material.dart';

const Color KAppColor = Color(0xffde554d);

List<Map> categories = [
  {
    "name": 'Culture',
    'icon': 'assets/icons/culture.png',
  },
  {
    "name": 'Dresses',
    'icon': 'assets/icons/dress.png',
  },
  {
    "name": 'Islam',
    'icon': 'assets/icons/muslim.png',
  },
];

List<Event> culturalAll =
    cultureTabCentralRegionItems + cultureTabWesternRegionItems;
List<Event> dinnerAll =
    dinnerTabCentralRegionItems + dinnerTabWesternRegionItems;
List<Event> islamAll = islamTabCentralRegionItems + islamTabWesternRegionItems;

List<Event> cultureTabCentralRegionItems = [
  Event(
    name: 'Gomesi_Busuuti',
    waist: 30.0,
    height: 150.0,
    shoulder: 40.0,
    image: 'images/img2.jpg',
    category: categories[0],
    location: 'Zai_Plaza Kampala',
    cost: 'USD 90',
    available: 12,
    tone: ["warm", "cool", "dark"],
    about:
        'Great wear for all kwanjula functions cutting across multiple regions in Uganda',
  ),
  Event(
    name: 'Bridal_Gomesi',
    waist: 30.0,
    height: 150.0,
    shoulder: 40.0,
    image: 'images/img12.jpg',
    category: categories[0],
    location: 'Zai_Plaza Kampala',
    cost: 'USD 100',
    available: 08,
    tone: ["warm"],
    about: 'The perfect attire to brighten up your special day',
  ),
  Event(
    name: 'Executive Gomesi',
    waist: 30.0,
    height: 150.0,
    shoulder: 40.0,
    image: 'images/img12.jpg',
    category: categories[0],
    location: 'Zai_Plaza Kampala',
    cost: 'USD 90',
    available: 23,
    tone: ["warm", "cool"],
    about:
        'The way you dress speaks alot about you. Get this glamourous attire for the utmost respect',
  ),
  Event(
    name: 'Ordinary_Gomesi',
    waist: 30.0,
    height: 150.0,
    shoulder: 40.0,
    image: 'images/img13.jpg',
    category: categories[0],
    location: 'Zai_Plaza Kampala',
    cost: 'USD 50',
    available: 3,
    tone: ["warm", "cool", "dark"],
    about: 'Embrace tradition always',
  ),
];

List<Event> cultureTabWesternRegionItems = [
  Event(
    name: 'Umushanana',
    waist: 30.0,
    height: 150.0,
    shoulder: 40.0,
    image: 'images/img8.jpg',
    category: categories[0],
    location: 'Zai_Plaza Kampala',
    cost: 'USD 80',
    available: 13,
    tone: ["cool"],
    about: 'Bringing out the western culture to light',
  ),
  Event(
    name: 'Umushanana',
    waist: 30.0,
    height: 150.0,
    shoulder: 40.0,
    image: 'images/img4.jpg',
    category: categories[0],
    location: 'Zai_Plaza Kampala',
    cost: 'USD 80',
    available: 10,
    tone: ["dark"],
    about: 'Bringing out the western culture to light',
  ),
  Event(
    name: 'Umushanana',
    waist: 30.0,
    height: 150.0,
    shoulder: 40.0,
    image: 'images/img6.jpg',
    category: categories[0],
    location: 'Zai_Plaza Kampala',
    cost: 'USD 80',
    available: 3,
    tone: ["warm"],
    about: 'Bringing out the western culture to light',
  ),
  Event(
      name: 'Umushanana',
      waist: 30.0,
      height: 150.0,
      shoulder: 40.0,
      image: 'images/img10.jpg',
      category: categories[0],
      location: 'Zai_Plaza Kampala',
      cost: 'USD 80',
      available: 3,
      tone: ["warm", "cool", "dark"],
      about: 'Bringing out the western culture to light'),
];

List<Event> profileEvents = [
  Event(
    name: 'Vumbula Festival',
    waist: 30.0,
    height: 150.0,
    shoulder: 40.0,
    image: 'assets/event2.jpg',
    category: categories[0],
    location: 'Jinja, Uganda',
    tone: ["warm", "cool", "dark"],
    cost: 'UGX 60-240k',
    available: 3,
    about:
        'Music festivals have come a long way since the psychedelic wig-outs of the \'60s. These days, there\'s a festival for everyone, even if you\'ve shunned most annual mud-fests in the past because you dance to disco and you don\'t like rock. Beyond the traditional London, UK and European festivals, there are fantastic international events from California\'s very Instagram-friendly Coachella to Japan\'s fabulous Fuji Rock, which prides itself on being the \'cleanest festival in the world\'Here are the 50 best music festivals to try before you die.',
  ),
  Event(
    name: 'Vumbula Festival',
    waist: 30.0,
    height: 150.0,
    tone: ["warm", "cool", "dark"],
    shoulder: 40.0,
    image: 'assets/event2.jpg',
    category: categories[0],
    location: 'Jinja, Uganda',
    cost: 'UGX 60-240k',
    available: 3,
    about:
        'Music festivals have come a long way since the psychedelic wig-outs of the \'60s. These days, there\'s a festival for everyone, even if you\'ve shunned most annual mud-fests in the past because you dance to disco and you don\'t like rock. Beyond the traditional London, UK and European festivals, there are fantastic international events from California\'s very Instagram-friendly Coachella to Japan\'s fabulous Fuji Rock, which prides itself on being the \'cleanest festival in the world\'Here are the 50 best music festivals to try before you die.',
  ),
  Event(
    name: 'Vumbula Festival',
    waist: 30.0,
    tone: ["warm", "cool", "dark"],
    height: 150.0,
    shoulder: 40.0,
    image: 'assets/event2.jpg',
    category: categories[0],
    location: 'Jinja, Uganda',
    cost: 'UGX 60-240k',
    available: 3,
    about:
        'Music festivals have come a long way since the psychedelic wig-outs of the \'60s. These days, there\'s a festival for everyone, even if you\'ve shunned most annual mud-fests in the past because you dance to disco and you don\'t like rock. Beyond the traditional London, UK and European festivals, there are fantastic international events from California\'s very Instagram-friendly Coachella to Japan\'s fabulous Fuji Rock, which prides itself on being the \'cleanest festival in the world\'Here are the 50 best music festivals to try before you die.',
  ),
  Event(
    name: 'Vumbula Festival',
    waist: 30.0,
    tone: ["warm", "cool", "dark"],
    height: 150.0,
    shoulder: 40.0,
    image: 'assets/event2.jpg',
    category: categories[0],
    location: 'Jinja, Uganda',
    cost: 'UGX 60-240k',
    available: 3,
    about:
        'Music festivals have come a long way since the psychedelic wig-outs of the \'60s. These days, there\'s a festival for everyone, even if you\'ve shunned most annual mud-fests in the past because you dance to disco and you don\'t like rock. Beyond the traditional London, UK and European festivals, there are fantastic international events from California\'s very Instagram-friendly Coachella to Japan\'s fabulous Fuji Rock, which prides itself on being the \'cleanest festival in the world\'Here are the 50 best music festivals to try before you die.',
  ),
  Event(
    name: 'Vumbula Festival',
    waist: 30.0,
    height: 150.0,
    tone: ["warm", "cool", "dark"],
    shoulder: 40.0,
    image: 'assets/event2.jpg',
    category: categories[0],
    location: 'Jinja, Uganda',
    cost: 'UGX 60-240k',
    available: 3,
    about:
        'Music festivals have come a long way since the psychedelic wig-outs of the \'60s. These days, there\'s a festival for everyone, even if you\'ve shunned most annual mud-fests in the past because you dance to disco and you don\'t like rock. Beyond the traditional London, UK and European festivals, there are fantastic international events from California\'s very Instagram-friendly Coachella to Japan\'s fabulous Fuji Rock, which prides itself on being the \'cleanest festival in the world\'Here are the 50 best music festivals to try before you die.',
  ),
];

List<Event> dinnerTabCentralRegionItems = [
  Event(
    name: 'Prom_Dress',
    waist: 30.0,
    height: 150.0,
    tone: ["warm", "cool", "dark"],
    shoulder: 40.0,
    image: 'images/img18.jpg',
    category: categories[0],
    location: 'Loozap_Kla-jinja road',
    cost: 'USD 120',
    available: 4,
    about:
        'Kateprom Sleeveless Party Homecoming Dress Short Royal Blue Prom Dresses With Zipper',
  ),
  Event(
    name: 'Prom_Dress',
    waist: 30.0,
    tone: ["warm", "cool", "dark"],
    height: 150.0,
    shoulder: 40.0,
    image: 'images/img16.jpg',
    category: categories[0],
    location: 'Loozap_Kla-jinja road',
    cost: 'USD 120',
    available: 5,
    about:
        'Our Dresses are all custom-made, so you order them in any size and color, and you can get your dress within 20-40 days after your payment.You can make the dress in standard size or custom size.',
  ),
  Event(
    name: 'Prom_Dress',
    waist: 30.0,
    height: 150.0,
    shoulder: 40.0,
    image: 'images/img19.jpg',
    category: categories[0],
    location: 'Loozap_Kla-jinja road',
    cost: 'USD 120',
    tone: ["cool", "dark"],
    available: 7,
    about:
        'Light Blue Prom Dresses Short Tea-Length Lace Applique Corset Back Formal Evening Dress Party Gowns Plus Size Vestido De Fiesta',
  ),
  Event(
    name: 'Prom_Dress',
    waist: 30.0,
    height: 150.0,
    shoulder: 40.0,
    image: 'images/img21.jpg',
    category: categories[0],
    location: 'Loozap_Kla-jinja road',
    cost: 'USD 120',
    available: 9,
    tone: [
      "warm",
    ],
    about:
        'Charming Dark Red Lace Cap Sleeve Prom Party Dresses. Elegant Knee Length. A Line Plus Size Celebrity Dresses Gala',
  ),
  Event(
    name: 'Cocktail_Dress',
    waist: 30.0,
    tone: ["warm", "dark"],
    height: 150.0,
    shoulder: 40.0,
    image: 'images/img18.jpg',
    category: categories[0],
    location: 'Loozap_Kla-jinja road',
    cost: 'USD 120',
    available: 10,
    about:
        'Vintage Elegant Knee Length Cocktail Dress. More size and colour options in stock',
  ),
  Event(
    name: 'Party_Dress',
    waist: 30.0,
    height: 150.0,
    tone: [
      "warm",
    ],
    shoulder: 40.0,
    image: 'images/img17.jpg',
    category: categories[0],
    location: 'Loozap_Kla-jinja road',
    cost: 'USD 120',
    available: 4,
    about: 'Short Navy Blue Knee Length Lace Party Dress Evening Dress',
  ),
  Event(
    name: 'Prom_Dress',
    waist: 30.0,
    height: 150.0,
    tone: ["dark"],
    shoulder: 40.0,
    image: 'images/img20.jpg',
    category: categories[0],
    location: 'Loozap_Kla-jinja road',
    cost: 'USD 120',
    available: 4,
    about:
        'Vintage Elegant Knee Length Cocktail Dress. More size and colour options in stock',
  ),
];

List<Event> dinnerTabWesternRegionItems = [
  Event(
    name: 'LOULOU',
    tone: ["warm", "dark"],
    waist: 30.0,
    height: 150.0,
    shoulder: 40.0,
    image: 'images/img31.jpg',
    category: categories[0],
    location: 'Loozap_Kla-jinja road',
    cost: 'USD 140',
    available: 2,
    about:
        'Black ruffle-detail sequin-embellished mini dress from LOULOU featuring sequin embellishment, ruffled detailing, round neck, concealed rear zip fastening, long sleeves and thigh-length.',
  ),
  Event(
    name: 'Party_Dress',
    waist: 30.0,
    height: 150.0,
    tone: [
      "warm",
      "cool",
    ],
    shoulder: 40.0,
    image: 'images/img26.jpg',
    category: categories[0],
    location: 'Loozap_Kla-jinja road',
    cost: 'USD 70',
    available: 1,
    about: 'Ball room LBECLEY Little Dress for Women Plus Size',
  ),
  Event(
    name: 'Party_Dress',
    waist: 30.0,
    tone: ["cool", "dark"],
    height: 150.0,
    shoulder: 40.0,
    image: 'images/img27.jpg',
    category: categories[0],
    location: 'Loozap_Kla-jinja road',
    cost: 'USD 50',
    available: 4,
    about:
        'CAICJ98 Semi Formal Dresses For Women. Off Shoulder High Split Evening Gown Long Party Maxi Dress Pink,XL',
  ),
  Event(
    name: 'Party_Dress',
    waist: 30.0,
    height: 150.0,
    tone: ["warm", "cool"],
    shoulder: 40.0,
    image: 'images/img22.jpg',
    category: categories[0],
    location: 'Loozap_Kla-jinja road',
    cost: 'USD 40',
    available: 3,
    about:
        'BEST HIGH-LOW FALL WEDDING GUEST DRESS. Jasambac Cocktail Party Dress',
  ),
  Event(
    name: 'Semi_formal Dress',
    waist: 30.0,
    height: 150.0,
    shoulder: 40.0,
    image: 'images/img23.jpg',
    category: categories[0],
    location: 'Loozap_Kla-jinja road',
    cost: 'USD 40',
    available: 4,
    tone: ["cool", "dark"],
    about:
        'Simple and classy semi formal dresses in various designs and colours',
  ),
  Event(
    name: 'Prom_Dress',
    waist: 30.0,
    height: 150.0,
    shoulder: 40.0,
    image: 'images/img28.jpg',
    tone: ["dark"],
    category: categories[0],
    location: 'Loozap_Kla-jinja road',
    cost: 'USD 65',
    available: 4,
    about:
        'Hi-Low Satin Long Ball Gown Scoop Neck Prom Dress with Pocket Appliques Formal Evening Party Gown. Comes in 12 different colours.',
  ),
];

List<Event> islamTabCentralRegionItems = [
  Event(
      waist: 30.0,
      height: 150.0,
      shoulder: 40.0,
      tone: [
        "warm",
      ],
      name: 'PARTY-HIJJAB',
      image: 'images/img41.jpg',
      category: categories[0],
      location: 'HAM TOWERS,LEVEL 1',
      cost: 'USD 30',
      available: 10,
      about: 'Elegance in Modesty: Embrace Islamic Fashion'),
  Event(
      waist: 30.0,
      height: 150.0,
      shoulder: 40.0,
      name: 'PARTY-HIJJAB',
      image: 'images/img42.jpg',
      category: categories[0],
      location: 'HAM TOWERS,LEVEL 1',
      cost: 'USD 30',
      tone: ["cool", "dark"],
      available: 7,
      about: 'Elegance in Modesty: Embrace Islamic Fashion'),
  Event(
      waist: 30.0,
      height: 150.0,
      shoulder: 40.0,
      name: 'PARTY-HIJJAB',
      image: 'images/img43.jpg',
      category: categories[0],
      location: 'HAM TOWERS,LEVEL 1',
      cost: 'USD 30',
      available: 5,
      tone: ["warm", "dark"],
      about: 'Elegance in Modesty: Embrace Islamic Fashion'),
  Event(
      waist: 30.0,
      height: 150.0,
      shoulder: 40.0,
      name: 'PARTY-HIJJAB',
      image: 'images/img44.jpg',
      category: categories[0],
      location: 'HAM TOWERS,LEVEL 1',
      cost: 'USD 30',
      available: 8,
      tone: ["cool", "dark"],
      about: 'Elegance in Modesty: Embrace Islamic Fashion'),
  Event(
      waist: 30.0,
      height: 150.0,
      shoulder: 40.0,
      name: 'PARTY-HIJJAB',
      image: 'images/img45.jpg',
      category: categories[0],
      location: 'HAM TOWERS,LEVEL 1',
      cost: 'USD 30',
      available: 10,
      tone: ["warm", "dark"],
      about: 'Elegance in Modesty: Embrace Islamic Fashion'),
  Event(
      waist: 30.0,
      height: 150.0,
      shoulder: 40.0,
      name: 'HIJJAB',
      image: 'images/img47.jpg',
      category: categories[0],
      location: 'HAM TOWERS,LEVEL 1',
      cost: 'USD 20',
      available: 10,
      tone: [
        "warm",
        "cool",
      ],
      about: 'Elegance in Modesty: Embrace Islamic Fashion'),
];

List<Event> islamTabWesternRegionItems = [
  Event(
      waist: 30.0,
      height: 150.0,
      shoulder: 40.0,
      name: 'MUSLIM-DRESS',
      tone: [
        "warm",
      ],
      image: 'images/img48.jpg',
      category: categories[0],
      location: 'HAM TOWERS,LEVEL 1',
      cost: 'USD 25',
      available: 10,
      about: 'Empowering Your Identity Through Style'),
  Event(
      waist: 30.0,
      height: 150.0,
      shoulder: 40.0,
      name: 'MUSLIM-DRESS',
      image: 'images/img49.jpg',
      category: categories[0],
      location: 'HAM TOWERS,LEVEL 1',
      cost: 'USD 25',
      available: 6,
      tone: ["warm", "dark"],
      about: 'Empowering Your Identity Through Style'),
  Event(
      waist: 30.0,
      height: 150.0,
      shoulder: 40.0,
      name: 'MUSLIM-DRESS',
      image: 'images/img50.jpg',
      category: categories[0],
      location: 'HAM TOWERS,LEVEL 1',
      cost: 'USD 25',
      available: 9,
      tone: ["cool", "dark"],
      about: 'Empowering Your Identity Through Style'),
  Event(
      waist: 30.0,
      height: 150.0,
      shoulder: 40.0,
      name: 'MUSLIM-DRESS',
      image: 'images/img56.jpg',
      category: categories[0],
      location: 'HAM TOWERS,LEVEL 1',
      cost: 'USD 25',
      tone: ["cool", "dark"],
      available: 10,
      about: 'Empowering Your Identity Through Style'),
  Event(
      waist: 30.0,
      height: 150.0,
      shoulder: 40.0,
      name: 'HIJJAB',
      tone: ["warm", "cool", "dark"],
      image: 'images/img51.jpg',
      category: categories[0],
      location: 'HAM TOWERS,LEVEL 1',
      cost: 'USD 40',
      available: 7,
      about: 'Graceful Attire for the Modern Muslimah'),
  Event(
      waist: 30.0,
      height: 150.0,
      shoulder: 40.0,
      name: 'HIJJAB',
      image: 'images/img52.jpg',
      category: categories[0],
      location: 'HAM TOWERS,LEVEL 1',
      cost: 'USD 40',
      available: 4,
      tone: [
        "cool",
      ],
      about: 'Graceful Attire for the Modern Muslimah'),
  Event(
      waist: 30.0,
      height: 150.0,
      shoulder: 40.0,
      name: 'HIJJAB',
      image: 'images/img53.jpg',
      category: categories[0],
      location: 'HAM TOWERS,LEVEL 1',
      cost: 'USD 50',
      available: 1,
      tone: [
        "warm",
        "cool",
      ],
      about: 'Graceful Attire for the Modern Muslimah'),
  Event(
      waist: 30.0,
      height: 150.0,
      shoulder: 40.0,
      tone: ["cool", "dark"],
      name: 'HIJJAB',
      image: 'images/img54.jpg',
      category: categories[0],
      location: 'HAM TOWERS,LEVEL 1',
      cost: 'USD 50',
      available: 1,
      about: 'Graceful Attire for the Modern Muslimah'),
  Event(
      waist: 30.0,
      height: 150.0,
      shoulder: 40.0,
      tone: ["dark"],
      name: 'HIJJAB',
      image: 'images/img55.jpg',
      category: categories[0],
      location: 'HAM TOWERS,LEVEL 1',
      cost: 'USD 50',
      available: 2,
      about: 'Graceful Attire for the Modern Muslimah'),
];
