// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdqKan63M3LUl1ZxvYOs7XDYFdUdf-RBA',
    appId: '1:988967495325:web:6e0f095d8804046a849674',
    messagingSenderId: '988967495325',
    projectId: 'kiwi-16045',
    authDomain: 'kiwi-16045.firebaseapp.com',
    storageBucket: 'kiwi-16045.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBprG-RoqnbeEIh37ltkVWkoUJcenTxUBA',
    appId: '1:988967495325:android:9fb670fc60ac1ba5849674',
    messagingSenderId: '988967495325',
    projectId: 'kiwi-16045',
    storageBucket: 'kiwi-16045.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB23mbmLOIMb6eO0Q2FQ24lbVEvhDg-WPQ',
    appId: '1:988967495325:ios:94ddd546b5a180c0849674',
    messagingSenderId: '988967495325',
    projectId: 'kiwi-16045',
    storageBucket: 'kiwi-16045.appspot.com',
    iosClientId: '988967495325-1jeolidg7jj6g471r5bcdtvdf6lt97ve.apps.googleusercontent.com',
    iosBundleId: 'com.eventsapp',
  );
}
